version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cheapair:
    image: cheapair:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
volumes:
  postgres-data:
    driver: local